modelcontextprotocol/registry

.gitignore
README.md
cmd/registry/main.go
internal/config/config.go

Updates the README with all of the env vars. I also changed `MCP_REGISTRY_IMPORT` to `MCP_REGISTRY_SEED_IMPORT` to be more descriptive and have it next to the `MCP_REGISTRY_SEED_FILE_PATH` env var in the README.
The old docs were out of date.
I built it and tested locally (including with docker).
No

docs: update env var docs in readme

---

api/README.md
api/openapi.yaml

This is a rough first pass at what the API shape should look like. Not meant to be final, we may not even merge this particular PR; just meant to give readers a sense of what we're going for to spark feedback conversations.

OpenAPI spec for official registry API

---

api/README.md
api/openapi.yaml

Refs #28. After some thinking, this tries for a 'best of both worlds' approach. Simple arguments can be present essentially as the original spec recommended. As discussed, we don't specify the args for `npx` and friends directly, so a simple package is merely...
```yaml
- name: my-api-mcp
packages:
- type: npm
name: "@c4312/my-api-mcp"
version: "0.0.1"
arguments:
- type: named
name: "api-key"
is_required: true
is_secret: true
```
However, I think we need to be able to specify runtime args in some cases, otherwise the registry eventually mirrors all docker configs and options which is not a great situation to be in. So, I suggest a `runtime_args` in the same format. Say I wanted that for npm, I could:
```yaml
- name: my-api-mcp
packages:
- type: npm
name: "@c4312/my-api-mcp"
version: …
```

feat: refine representation of commands in the API

---

Dockerfile

Updated the `Dockerfile` to use the new seed file `seed_2025_05_16.json` instead of the old `seed.json`.

feat: use new seed file in docker build

---

docker-compose.yml

To use the publisher tool you need to have these env vars set in the server.

fix: add needed env vars to docker-compose.yml

---

api/README.md
api/openapi.yaml
tools/publisher/mcp.json

I realized a handful of our examples were still using the old syntax that we are no longer using, which could cause confusion for folks who don't have the context that we are pushing forward with the reverse DNS scheme.

Fix naming to use reverse DNS instead of deprecated `@` syntax

---

tools/publisher/README.md
tools/publisher/auth/README.md
tools/publisher/auth/github/oauth.go
tools/publisher/auth/interface.go
tools/publisher/main.go

This pull request introduces significant updates to the authentication system for the MCP Registry Publisher Tool. The changes focus on transitioning to an interface-based authentication system, implementing GitHub OAuth device flow as the default authentication method, and restructuring the codebase for better modularity and extensibility.
Adding an interface to the publishing CLI, so that it'll be easier to add more auth methods as they become available.

Publish Auth Interface 

---

docs/openapi.yaml

This makes repository optional as per #111.

fix: make repository optional in openapi spec

---

README.md
cmd/registry/main.go
internal/config/config.go

Add support for specifying database type (MongoDB or in-memory database).
The README states that MCP Registry supports both MongoDB and in-memory databases, but does not provide the capability to specify which database type to use.
https://github.com/modelcontextprotocol/registry/blob/5d9171bdccf579398273806a7067cda29e88363c/README.md?plain=1#L19
This PR addresses this limitation by adding explicit database type configuration through the `DATABASE_TYPE` environment variable, allowing users to choose between `mongodb` and `memory` database types in a standardized way.
Yes
```console
$ export MCP_REGISTRY_DATABASE_TYPE="memory"
$ ./scripts/test_endpoints.sh
Testing health endpoint: http://localhost:8080/v0/health
Status Code: 200
Response:
{
"status": "ok",
"github_client_id": ""
}
Health …
```

feat(config): specify to use in-memory database

---

docs/server-json/README.md
docs/server-json/examples.md
docs/server-json/schema.json

This is a first cut at properly defining the `server.json` file. We have been working out details of the shape for a while, but to-date it has only been implicitly documented as the OpenAPI response to `/servers/:id`, which is not an exact definition due to some registry-specific details (like `id` and `is_latest`).
Edit: as-written in this PR, this is a more constrained version of `server.json` that the Registry intends to support at-launch. The broader `server.json` may have looser constraints, for example no `enum` constraint on `source=github,gitlab`. See https://github.com/modelcontextprotocol/registry/issues/155
---
There are a variety of use cases where a _static representation of an MCP server_ is necessary:
- Discoverability on a centralized registry (i.e. our official Registry …

First cut at server.json

---

docs/README.md
docs/architecture.md
docs/design_principles.md
docs/faq.md
docs/new_package_registry.md
docs/openapi.yaml
docs/server-json/examples.md
docs/server-json/schema.json
tools/publisher/server.json

This resolves https://github.com/modelcontextprotocol/registry/issues/126.
As of .NET 10 Preview 6 (releasing on July 8th, 2025), .NET has a single-shot command similar to npx and uvx. It is called `dnx`.
This allows .NET tool packages hosted on NuGet.org to be executed much like npm or PyPI packages. 
I have added NuGet to a lot of the places Python and npm exist today. If it is too many places, I am happy to trim it down!
I a sample MCP server hosted on nuget.org and running in my VS Code using `dnx`.
None.
- Add `nuget` as a supported `registry_name`
- Add `dnx` as an example `runtime_hint`
- Add a guide on how to add a new package registry

Add NuGet to the MCP Registry, similar to npm and Python

---

data/seed_2025_05_16.json

Closes https://github.com/modelcontextprotocol/registry/issues/136
- For each unknown registry, try to resolve the name on npm, pypi, and docker, and use that when available
- Filter out unknowns emove any servers that lack packages afterwards

Resolve packages and remove unknown registries

---

docs/server-json/repository_references.md

Resolve https://github.com/modelcontextprotocol/registry/issues/173
Copilot fixed my spelling mistakes.
None.
Ideally the `id` would be populated by the publisher CLI tool "on the way out" and MCP Registry would validate the `id`, perhaps using the token used for auth in the case of private repositories.

Add documentation for the repository section

---

.gitignore
docs/server-json/examples.md
docs/server-json/schema.json
docs/server-registry-api/examples.md
docs/server-registry-api/openapi.yaml
internal/model/model.go
tools/publisher/main.go
tools/publisher/server.json
tools/validate-examples/main.go

The following PR adds a new server `status` field to support the status of servers, like deprecated or active
Details:
* Add status field to server.json schema with 'active' and 'deprecated' values
* Update OpenAPI spec to include status field in Server responses
* Add ServerStatus enum and field to Go model structs
* Update examples to demonstrate status field usage (`active` and `deprecated`)
Since this is my first PR there's a good chance I might have missed something so I'll appreciate any feedback to make this and any PRs in the future easier for you to review 😃 
Fixes: #181
The main goal is to have a way for server authors to notify registry consumers that a server may no longer be maintained and shouldn't be considered for using.

Add a status field indicating if a server is deprecated or active

---

.gitignore

The following PR removes the gitignore entry for `publisher` since this means we gitignore all folders and files named `publisher`. 
My assumption is the intent for this was to just ignore binaries named `publisher` but currently that binary is going to be located at `tools/publisher/bin/mcp-publisher` and the **/bin pattern already ignores all bin/ directories (taken from the build.sh).

Do not gitignore all folders and files named publisher

---

.gitignore
Makefile

- Remove registry binary from git tracking
- Update Makefile to output binaries to bin/ directory  
- Fix .gitignore to properly exclude bin/ directory and all binaries
This follows Go best practices by placing all compiled binaries in the bin/ directory.

Remove tracked binaries and fix build output directory

---

Dockerfile

Create a separate step in the Docker image to install the dependencies. This makes local dev a bunch faster, because Docker doesn't redownload all the dependencies each time you make a small file changes.

build: Optimize Dockerfile by splitting out dependency installation and go build

---

internal/api/handlers/v0/auth/http.go
internal/api/handlers/v0/auth/http_test.go
internal/api/handlers/v0/auth/main.go
internal/model/model.go
tools/publisher/README.md
tools/publisher/auth/common.go
tools/publisher/auth/dns.go
tools/publisher/auth/http.go
tools/publisher/main.go

Add HTTP-based authentication to prove domain ownership, similar to https://github.com/modelcontextprotocol/registry/pull/238's DNS authentication but using HTTPS well-known URIs instead of DNS TXT records.
Fixes #280
Some organizations don't have easy access to DNS records, but can easily deploy web assets. They would therefore prefer to be able to complete a HTTP challenge rather than a DNS one to authenticate to the registry.
This would in some way mirror ACME challenges: where you can do a DNS-01 or a HTTP-01 challenge.
- Tested locally by stubbing out the HTTP getter
- Added unit tests
None
I concern I had when building this that it might expose us to SSRF attacks.
I think on reflection this is not a significant problem:
- We only GET a fixed file `.well-known/mcp-registry-auth` …

auth: Add HTTP-based authentication support to validate domain ownership

---

docs/new_package_registry.md
docs/server-json/README.md
docs/server-json/examples.md
docs/server-json/registry-schema.json
docs/server-json/repository_references.md
docs/server-json/server.schema.json
docs/server-registry-api/openapi.yaml
internal/model/model.go
tools/publisher/main.go
tools/publisher/server.json
tools/validate-examples/main.go
tools/validate-schemas/main.go

- Add optional `$schema` property to ServerDetail specification
- Update JSON Schema, OpenAPI spec, Go models, examples, and publisher template
- Enable schema versioning and IDE validation support
- Added `$schema` as optional string property with URI format in specs
- Updated Go ServerDetail struct with new Schema field
- Added `$schema` to examples and publisher template
- Copy schema file to ../static for GitHub Pages hosting
Fixes #139

Add  $schema to server.json specification to enable versioning, IDE autocomplete

---

.github/workflows/ci.yml

- Remove Codecov integration from CI workflow
- Upload coverage reports as GitHub Actions artifacts instead
- Eliminates external dependency and potential security/reliability issues
Closes #309

Replace Codecov with GitHub Actions artifacts

---

docs/server-registry-api/openapi.yaml

This PR addresses #300 by adding explicit versioning to the MCP Registry API OpenAPI specification.
- Added `version: "2025-07-09"` field to the `info` section of the OpenAPI specification
- Maintains consistency with existing date-based versioning used across all schema files
As outlined in #300, the OpenAPI spec was missing an explicit version field, which could lead to:
- Compatibility issues as the API evolves
- Lack of clarity for API consumers
- Missing functionality in OpenAPI tooling that expects a version field
This follows the MCP specification's date-based versioning approach.
Closes #300

feat: add version field to OpenAPI specification

---

docs/server-json/server.schema.json
internal/api/handlers/v0/edit.go
internal/api/handlers/v0/edit_test.go
internal/api/handlers/v0/publish_test.go
internal/api/router/v0.go
internal/database/database.go
internal/database/memory.go
internal/database/postgres.go
internal/model/model.go
internal/service/fake_service.go
internal/service/registry_service.go
internal/service/service.go

Implements `PUT /v0/servers/{id}` admin edit endpoint to address part of issue #182, providing an API-based solution for server moderation without requiring direct database access.
- **New endpoint**: `PUT /v0/servers/{id}` for editing existing servers
- **Security**: Uses existing JWT auth with `PermissionActionEdit` permissions  
- **Anti-undelete protection**: Added `ServerStatusDeleted` status that cannot be reverted
- **Full implementation**: Database, service, API, and comprehensive test coverage
- Mark malicious servers as `deleted` for takedown
- Update server metadata for moderation actions
Related to: https://github.com/modelcontextprotocol/registry/issues/182 (but that is not _done_ yet because we need admins to be able to login (probably with #283), and need to add docs on how …

feat: add admin edit endpoint for server moderation

---

internal/api/handlers/v0/edit.go
internal/api/handlers/v0/edit_test.go
internal/api/handlers/v0/publish.go
internal/api/handlers/v0/publish_integration_test.go
internal/api/handlers/v0/publish_test.go
internal/api/handlers/v0/servers.go
internal/api/handlers/v0/servers_test.go
internal/api/handlers/v0/telemetry_test.go
internal/database/database.go
internal/database/import.go
internal/database/import_test.go
internal/database/memory.go
internal/database/postgres.go
internal/service/fake_service.go
internal/service/registry_service.go
internal/service/service.go
internal/validators/validators.go
internal/validators/validators_test.go
pkg/api/v0/types.go

This PR renames the API paths from v1 to v0 to align with the actual API versioning scheme.

Rename api/v1 -> api/v0 to match API paths

---

README.md

Fixed grammar issues in the README description for better readability.
The registry description had a sentence fragment and missing article that made it harder to read smoothly.
N/A - text-only changes to documentation.
None.
Changed ". Like an app store for MCP servers." to ", like an app store for MCP servers" (joined sentence fragment) and "In future" to "In the future" (added missing article).

docs: fix grammar in README description

---

docs/server-json/examples.md
internal/validators/validators_test.go

- Updates all server.json examples to use `io.github` namespace instead of `com.github`
- Fixes validator test case to use proper domain format
- Aligns with standard reverse domain name convention for GitHub-hosted projects
This change improves consistency across documentation examples and follows established naming conventions.

Update examples.md for more realism

---

deploy/pkg/k8s/monitoring.go

Consistency with https://staging.registry.modelcontextprotocol.io/ URL format (i.e. `<env>.<service>`, rather than `<service>.<env>`
Deployed in staging
Grafana URL changes, but it's only just launched so fine.

deploy: fix: update Grafana ingress host format for consistency

---

deploy/README.md
deploy/pkg/k8s/ingress.go

- Removed Azure deployment section and references from README
- Updated project structure to reflect current GCP prod/staging configs  
- Removed Azure Load Balancer annotation from ingress controller
- Updated provider documentation to show GCP and local options only
- Added monitoring.go to project structure documentation
This cleans up outdated Azure/AKS deployment configuration that is no longer used, leaving only the current GCP-based deployment structure.

Remove Azure/AKS deployment configuration from deploy

---

internal/validators/constants.go
internal/validators/validators.go
internal/validators/validators_test.go

Closes a validation gap that allowed servers to be published with unsupported registry types and base URLs.
- **Registry Type Validation**: Only allow `npm`, `pypi`, `oci`, `nuget`, `mcpb`
- **Registry Base URL Validation**: Enforce strict allowlist of official registry URLs
- **Required Fields**: Registry type and base URL required when package identifier provided
- **Comprehensive Tests**: Clear test structure showing valid vs invalid cases side-by-side
- `npm` → `https://registry.npmjs.org`
- `pypi` → `https://pypi.org`
- `oci` → `https://docker.io` 
- `nuget` → `https://api.nuget.org`
- `mcpb` → `https://github.com` or `https://gitlab.com`
All other combinations are rejected with clear error messages.

Validate server registry urls are allowlisted for that registry type

---

.env.example
internal/config/config.go

Cleanup unused configuration, to avoid confusing ourselves in future
Everything still runs happily locally, also searched for references
None

config: remove unused database and logging configuration options

---

cmd/publisher/commands/init.go
data/seed.json
docs/server-json/examples.md
docs/server-json/server.schema.json
internal/api/handlers/v0/publish_integration_test.go
internal/api/handlers/v0/publish_registry_validation_test.go
internal/api/handlers/v0/publish_test.go
internal/service/registry_service_test.go
internal/validators/utils.go
internal/validators/validators.go
internal/validators/validators_test.go
pkg/api/v0/types.go
pkg/model/types.go

The following PR:
* Adds a new `transport` type used in Package and Remotes
* Added `docker` to the `runtime_hint` examples
* Added support for templated URLs. It is available for streamable-http and sse transports for Packages. I didn't thought of reasons to have this for Remotes, but we can enable it if needed.
* Added validation for templated URLs so we can ensure all referenced placeholder variables are available. 
* For streamable-http and SSE transport types the URL is now a required property
* Updated the publisher init command to reflect these changes
* Updated the seed.json file
* Added unit tests for the transport type related changes
* Updated the server.json schema and the external pkg structs to reflect the new transport type
* Updated the examples
Thanks to @kkkarthik for …

Reflect the latest registry changes in openapi.yaml

---

docs/guides/publishing/publish-server.md

Simplifies the installation instructions in the publisher guide by:
- Auto-detecting platform using `uname` and PowerShell built-ins for a single copy-paste command
- Moving build-from-source to a collapsible details section to emphasize the recommended pre-built binary approach
- Removing unnecessary `chmod +x` since tar preserves executable permissions
- Adding explicit support for WSL
This makes it much easier for users to get started - they can now just copy one command instead of picking from 4+ platform-specific options.

docs: Simplify publisher CLI installation instructions

---

internal/database/postgres.go

summary
- use the indexed primary key (`id`) for `getbyid`, `updateserver`, and list ordering/cursor, instead of extracting `_meta...id` from jsonb
- in `updateserver`, error if the body tries to change the id; set `meta.official.id` when missing
changes
- database: `getbyid` → `where id = $1`
- database: `updateserver` → `where id = $2`; fail on id mismatch; set id if missing
- database: `list` orders by `id` and paginates via `id > $cursor`
- no schema or api changes
<details>
<summary>performance</summary>
- env: repo docker compose postgres, 5k–10k rows, warm cache
- getbyid: `id` ≈ 0.02 ms vs jsonb path ≈ 0.80 ms
- update: `id` ≈ 0.15 ms vs jsonb path ≈ 0.78 ms
- list (limit 100): order by `id` ≈ 0.13 ms vs jsonb path id ≈ 2.24 ms (~17x slower)
</details>
<details>
<summary>explain …

perf(db): use pk id for lookups and ordering

---

go.mod
go.sum
internal/database/postgres.go

The following PR should fix the recent "conn busy" issue caused by the PostgreSQL implementation using a single database connection (*pgx.Conn) instead of a connection pool (*pgxpool.Pool). When multiple concurrent requests try to access the endpoint, they would conflict trying to use the same connection.
Builds locally
No
Related to #400, #405 and #407

Use a connection pool instead of a single DB connection

---

docs/reference/faq.md

We just want to highlight that Docker Hub will support this project with updates to the `docker mcp` cli and the [mcp hub](https://hub.docker.com/mcp) catalog.

Add Docker Hub to list of supported registries

---

internal/validators/registries/npm.go
internal/validators/registries/npm_test.go

Adding validation for version and identifier for packages.
While debugging a bug, I found out that we need exact version to be there in package to fetch from npm, otherwise we won't be able to parse the response as it returns all versions. Even if we do, we still need to go and figure out which version have the mcpname associated with while iterating over all versions. So, we should make mandatory to have identifier and version present in the given package object if we want to validate package association with registries.
UTs.

Check for version and identifier for npm packages

---

docs/guides/publishing/publish-server.md

NuGet package deployment option is mentioned in the [guidelines](https://github.com/modelcontextprotocol/registry/blob/main/docs/guides/publishing/publish-server.md#configure-deployment-methods) for publishing MCP Server to the registry, but `NuGet` is not mentioned in the top of the page.
Documentation update
No breaking changes

Add NuGet to package deployment options

---

deploy/pkg/k8s/monitoring.go
deploy/pkg/k8s/postgres.go
deploy/pkg/providers/gcp/provider.go

Bumps the node machine type from e2-small to e2-standard-2 to provide more CPU and memory headroom for the cluster.
Also disables PodDisruptionBudgets (PDBs) for single-instance PostgreSQL clusters to prevent node upgrade operations from becoming blocked.
- Increase GKE node machine type from e2-small to e2-standard-2
- Set `enablePDB: false` for registry and Grafana PostgreSQL clusters
The machine type increase addresses resource constraints causing deployment failures.
The PDB change prevents a specific issue where GKE node upgrades get stuck when trying to drain nodes containing single-instance PostgreSQL pods. With `minAvailable: 1` PDBs, evicting the only database instance violates the availability requirement, blocking the drain operation indefinitely. Disabling PDBs for these …

Increase GKE node size to e2-standard-2

---

deploy/README.md

Added documentation for configuring kubectl to access existing GKE clusters for both production and staging environments.

docs: add kubectl configuration instructions for GKE access

---

complete.md
internal/database/database.go
internal/database/memory.go
internal/database/migrations/007_add_publish_constraints.sql
internal/database/postgres.go
internal/service/registry_service.go
internal/service/registry_service_test.go

Fixes race conditions in concurrent server publishing that could result in data integrity violations:
- Multiple versions marked as `isLatest=true` for the same server
- Duplicate (serverId, version) combinations
- Same server name assigned different serverIDs
Uses two complementary approaches for correctness:
- Serializes concurrent publishes per server name using `pg_advisory_xact_lock`
- Uses FNV-1a hash to convert server name to lock ID
- Transaction-scoped locks auto-release on commit/rollback
- **Required after #465**: The serverId introduction means concurrent publishes must atomically coordinate whether to reuse an existing serverId (for additional versions) or generate a new one (for first version). Without locks, race conditions would assign different serverIDs to versions of …

Fix race conditions in concurrent server publishing

---

internal/api/handlers/v0/auth/oidc.go
internal/api/handlers/v0/auth/oidc_test.go
internal/config/config.go

Fixes a concurrent map access vulnerability in the OIDC handler that could cause remote unauthenticated DoS.
- Removed OIDC authorization flow endpoints ( and )
- Removed the unsynchronized  map that caused the data race
- Kept only the OIDC token exchange endpoint ()
- Simplified  by removing OAuth2 flow dependencies
The  map was being accessed concurrently by the start (write) and callback (read/delete) endpoints without synchronization, causing runtime panics. Since the token exchange flow doesn't require session state, removing the authorization flow eliminates the vulnerability entirely.

Remove OIDC authorization flow to fix data race vulnerability

---

docs/guides/publishing/github-actions.md

This pull request makes a minor update to the documentation for installing the MCP Publisher in GitHub Actions workflows. The change updates the installation command to use version 1.1.0 of the MCP Publisher instead of version 1.0.0.
The `mcp-publisher` version in GitHub Actions has to be updated so it can publish the MCP server to the newest version of MCP Registry.
Documentation update only. No test needed.
No
None

docs: update download link of mcp-publisher in GitHub Actions to 1.1.0

---

docs/reference/api/openapi.yaml

This seems to be a regresion after rename, those fields were originally required:
https://github.com/modelcontextprotocol/registry/blob/8d7e471fd3f28fbaccb69f69e8b39483ac4c58c3/docs/server-registry-api/openapi.yaml#L247-L252
In https://static.modelcontextprotocol.io/schemas/2025-09-16/server.schema.json, those fields are also required.
No

fix(spec): registryType, identifier, version should be required fields

---

internal/api/openapi_compliance_test.go

The following PR adds a simple unit test to ensure the served API handlers are a superset of the reference OpenAPI schema. We can extend/update this later to have a more thorough check, i.e. inputs, outputs, return codes, etc.
Fixes: https://github.com/modelcontextprotocol/registry/issues/567

Ensure registry API implements the reference openapi schema

---

docs/community-projects.md
docs/guides/publishing/github-actions.md

Add Community Resources section to GitHub Actions guide referencing OtherVibes/mcp-publish-action as requested in discussion #518.
- Add "Community Resources" section to `docs/guides/publishing/github-actions.md`
- Include reference to OtherVibes/mcp-publish-action with appropriate disclaimers
- Provide example usage and key features
- Position after Tips section for discoverability
- Structure allows for future community tool additions
This addresses the community request in discussion #518 where @OtherVibes suggested adding a reference to their reusable GitHub Action in the publishing docs. The maintainers (@tadasant, @domdomegg) approved adding a community resources section with appropriate disclaimers.
The implementation follows the original request to add the reference specifically …

docs: add community resources section with OtherVibes/mcp-publish-action

---

.github/workflows/cancel-pulumi-lock.yml
.github/workflows/deploy.yml

Addresses the security concern where secrets were directly interpolated in GitHub Actions run commands across multiple workflows.
Following [GitHub's security best practices](https://docs.github.com/en/actions/reference/security/secure-use#use-an-intermediate-environment-variable), secrets are now passed through intermediate environment variables (matching the secret names: `PULUMI_STAGING_PASSPHRASE` and `PULUMI_PROD_PASSPHRASE`) before being written to files.
**deploy.yml:**
- Fixed staging deployment (line 92)
- Fixed production deployment (line 131)
**cancel-pulumi-lock.yml:**
- Fixed staging lock cancellation (line 62)
- Fixed production lock cancellation (line 70)
This approach:
- Fixes the security issue with direct secret interpolation in 4 locations
- Maintains compatibility with …

Use intermediate env vars for Pulumi passphrases

---

deploy/Pulumi.gcpProd.yaml
deploy/README.md
deploy/pkg/k8s/registry.go
docs/guides/contributing/releasing.md

The following PR moves away from automatically promoting latest releases to production in favour of specifying the released version explicitly via a PR & Review process.
Still sets the image tag to latest for now so we can enable it separately whenever we decide 👍

Enable a gitops way of promoting to prod

---

docs/reference/server-json/server.schema.json

- Clarified `value` field description to remove incorrect 'default' wording
- Improved `valueHint` description to clarify its form and purpose (labels and variable substitution)
- Fixed NamedArgument `description` to use correct flag syntax (--flag {value})
- Enhanced `default` field description with guidance on valid values and when to use placeholder instead
- Added optional Input `placeholder` field for input guidance and examples
After implementing a configuration UX for the registry supporting all schema elements, performing schema validation on all published servers and analyzing failures, and hand reviewing approximately a hundred server configurations, I found a number of concerning issues (essentially misconfigurations, verified by the docs of the server in question, which often …

Recommended server.json schema field descriptions and new Input placeholder property

---

data/seed.json
docs/reference/api/openapi.yaml
docs/reference/server-json/server.schema.json
internal/validators/constants.go
internal/validators/validators.go
internal/validators/validators_test.go
pkg/api/v0/types.go
pkg/model/types.go

Implements icon support based on the Model Context Protocol specification, allowing servers to specify display icons with optional size, MIME type, and theme variants.
- Add `Icon` type to `pkg/model/types.go` with struct tags for automatic API validation
- Add `icons` field to `ServerJSON` in `pkg/api/v0/types.go`
- Add icon validation in `internal/validators/validators.go`:
- Only HTTPS URLs allowed (no HTTP or data URIs)
- Maximum URL length of 255 characters
- Validates absolute URLs with proper scheme
- Update JSON schema and OpenAPI documentation with Icon definitions
- Add comprehensive test cases for icon validation
- Add example icon to seed.json (Airtable server)
- Change `websiteUrl` validation to HTTPS-only for consistency
The implementation uses a two-layer validation …

Add icon support to server.json schema

---

Makefile
docs/reference/api/openapi.yaml
docs/reference/server-json/server.schema.json
tools/extract-server-schema/main.go

This PR adds a Go tool that extracts the ServerDetail schema from openapi.yaml and generates server.schema.json, ensuring the two specs stay in sync.
- **Go tool** at `tools/extract-server-schema/` that auto-discovers all schemas referenced by ServerDetail and extracts them from OpenAPI
- **make targets**: `generate-schema` (generates schema) and `check-schema` (verifies sync)
- `check-schema` is now included in `make validate` and `make check`
The initial auto-generated schema lost many important validation rules and descriptive guidance from the hand-crafted version. The OpenAPI spec has been updated to preserve:
**Security & Descriptions:**
- Command injection security warning on Arguments
- Detailed field descriptions with usage guidance  
- `placeholder` field for Input schema …

Add tooling to auto-generate server.schema.json from OpenAPI spec
